### ISSUE TITLE
CCBlade unit test fails

### ISSUE THREAD

**Issue by matsupe** [WISDEM/CCBlade#1]
The installation of CCBlade is difficult. 

Could you please provide more details about the Python software you used on your system? 

I installed:

MinGW gfortran Fortran compiler, Python 2.7, NumPy, SciPy, and zope.interface (last 3 for Python 2.7) on my Windows PC. 

The installation was successful but I get the following error when I run the unit test "python test/test_ccblade.py" : 

Matias@MATIAS-PC C:\CCBlade
$ python test\test_ccblade.py
F
======================================================================
FAIL: test_thrust_torque (__main__.TestNREL5MW)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test\test_ccblade.py", line 117, in test_thrust_torque
    np.testing.assert_allclose(Q[idx]/1e6, Qref[idx]/1e3, atol=0.15)
  File "C:\Python27\lib\site-packages\numpy\testing\utils.py", line 1297, in assert_allclose
    verbose=verbose, header=header)
  File "C:\Python27\lib\site-packages\numpy\testing\utils.py", line 665, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Not equal to tolerance rtol=1e-07, atol=0.15

(mismatch 100.0%)
 x: array([ 0.770317,  0.500736,  0.424291,  0.357537,  0.296075,  0.257044,
        0.324109,  0.397444,  0.262967,  7.985468,  7.890789,  7.829099])
 y: array([ 0.0588,  0.2502,  0.5443,  0.9395,  1.4181,  1.9569,  2.4745,
        3.0511,  3.8813,  4.1801,  4.1801,  4.1801])

----------------------------------------------------------------------
Ran 1 test in 0.983s

FAILED (failures=1)

Matias@MATIAS-PC C:\CCBlade
$

**Comment by andrewning** [comment]
This is not an installation failure, but a testing one.  I am seeing the same issue.  Something must have changed in one of the recent commits.  Give me a few days to look into this.

**Comment by andrewning** [comment]
I've now fixed this issue.  Thanks for pointing it out.  Please update (and update airfoilprep)
