### ISSUE TITLE
CCBlade running test

### ISSUE THREAD

**Issue by Jjzm99** [WISDEM/CCBlade#10]
Hello
I was trying to install ccblade using the comand python setup.py install, and after the installation was completed I started the test with the comand python test/test_ccblade.py but an error appear 
Import Error: DLL load failed: It couldnt to find the esoecified module

If you ccould help me with this, I ll apreciated so much 
Im trying to use this program for a research .
Thanks for your time

**Comment by Jjzm99** [comment]
![captura](https://user-images.githubusercontent.com/43582676/46031679-2d886480-c0bf-11e8-9701-7c9a0ea445ac.JPG)

**Comment by Jjzm99** [comment]
windows 7 ultimate
anaconda 2.7 x64
![captura](https://user-images.githubusercontent.com/43582676/46031820-9a9bfa00-c0bf-11e8-9f5a-2739c8aef8d5.JPG)

**Comment by evan-gaertner** [comment]
It's failing to load _bem which is the compiled fortran blade element momentum solver. The problem is almost definitely your fortran compiler.  Make sure you have MinGW installed and properly configured as discussed here https://nwtc.nrel.gov/WISDEM and https://nwtc.nrel.gov/system/files/Windows%20OpenMDAO%20Install%20Tips_04062015.pdf

If you're still running into problems after fixing your compiler, please share the full output from reinstalling CCBlade using
python setup.py install --force

**Comment by Jjzm99** [comment]
(base) C:\CCBlade-master\CCBlade-master>python setup.py install --force
running install
running bdist_egg
running egg_info
running build_src
build_src
building py_modules sources
building extension "_bem" sources
f2py options: []
  adding 'build\src.win32-2.7\build\src.win32-2.7\fortranobject.c' to sources.
  adding 'build\src.win32-2.7\build\src.win32-2.7' to include_dirs.
build_src: building npy-pkg config files
writing requirements to src\CCBlade.egg-info\requires.txt
writing src\CCBlade.egg-info\PKG-INFO
writing top-level names to src\CCBlade.egg-info\top_level.txt
writing dependency_links to src\CCBlade.egg-info\dependency_links.txt
reading manifest file 'src\CCBlade.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no directories found matching 'docs\_build\html'
writing manifest file 'src\CCBlade.egg-info\SOURCES.txt'
installing library code to build\bdist.win32\egg
running install_lib
running build_py
running build_ext
customize MSVCCompiler
customize MSVCCompiler using build_ext
get_default_fcompiler: matching types: '['gnu', 'intelv', 'absoft', 'compaqv', '
intelev', 'gnu95', 'g95', 'intelvem', 'intelem', 'flang']'
customize GnuFCompiler
Could not locate executable g77
Could not locate executable f77
customize IntelVisualFCompiler
Could not locate executable ifort
Could not locate executable ifl
customize AbsoftFCompiler
Could not locate executable f90
customize CompaqVisualFCompiler
Could not locate executable DF
customize IntelItaniumVisualFCompiler
Could not locate executable efl
customize Gnu95FCompiler

**Comment by Jjzm99** [comment]
(base) C:\CCBlade-master\CCBlade-master>python setup.py install --force
running install
running bdist_egg
running egg_info
running build_src
build_src
building py_modules sources
building extension "_bem" sources
f2py options: []
  adding 'build\src.win32-2.7\build\src.win32-2.7\fortranobject.c' to sources.
  adding 'build\src.win32-2.7\build\src.win32-2.7' to include_dirs.
build_src: building npy-pkg config files
writing requirements to src\CCBlade.egg-info\requires.txt
writing src\CCBlade.egg-info\PKG-INFO
writing top-level names to src\CCBlade.egg-info\top_level.txt
writing dependency_links to src\CCBlade.egg-info\dependency_links.txt
reading manifest file 'src\CCBlade.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no directories found matching 'docs\_build\html'
writing manifest file 'src\CCBlade.egg-info\SOURCES.txt'
installing library code to build\bdist.win32\egg
running install_lib
running build_py
running build_ext
customize MSVCCompiler
customize MSVCCompiler using build_ext
get_default_fcompiler: matching types: '['gnu', 'intelv', 'absoft', 'compaqv', '
intelev', 'gnu95', 'g95', 'intelvem', 'intelem', 'flang']'
customize GnuFCompiler
Could not locate executable g77
Could not locate executable f77
customize IntelVisualFCompiler
Could not locate executable ifort
Could not locate executable ifl
customize AbsoftFCompiler
Could not locate executable f90
customize CompaqVisualFCompiler
Could not locate executable DF
customize IntelItaniumVisualFCompiler
Could not locate executable efl
customize Gnu95FCompiler
Could not locate executable gfortran
Could not locate executable f95
customize G95FCompiler
Could not locate executable g95
customize IntelEM64VisualFCompiler
customize IntelEM64TFCompiler
Could not locate executable efort
Could not locate executable efc
customize PGroupFlangCompiler
don't know how to compile Fortran code on platform 'nt'
warning: build_ext: f77_compiler=None is not available.

copying build\temp.win32-2.7\Release\extra-dll\libbem.C3FIULAIMCZY6IKUG6FT7UYYIO
MUMWMW.gfortran-win32.dll -> build\lib.win32-2.7\CCBlade\.libs
creating build\bdist.win32\egg
creating build\bdist.win32\egg\ccblade
creating build\bdist.win32\egg\ccblade\.libs
copying build\lib.win32-2.7\ccblade\.libs\libbem.C3FIULAIMCZY6IKUG6FT7UYYIOMUMWM
W.gfortran-win32.dll -> build\bdist.win32\egg\ccblade\.libs
copying build\lib.win32-2.7\ccblade\ccblade.py -> build\bdist.win32\egg\ccblade
copying build\lib.win32-2.7\ccblade\ccblade_component.py -> build\bdist.win32\eg
g\ccblade
copying build\lib.win32-2.7\ccblade\__init__.py -> build\bdist.win32\egg\ccblade

copying build\lib.win32-2.7\ccblade.py -> build\bdist.win32\egg
copying build\lib.win32-2.7\_bem.pyd -> build\bdist.win32\egg
byte-compiling build\bdist.win32\egg\ccblade\ccblade.py to ccblade.pyc
byte-compiling build\bdist.win32\egg\ccblade\ccblade_component.py to ccblade_com
ponent.pyc
byte-compiling build\bdist.win32\egg\ccblade\__init__.py to __init__.pyc
byte-compiling build\bdist.win32\egg\ccblade.py to ccblade.pyc
creating stub loader for _bem.pyd
byte-compiling build\bdist.win32\egg\_bem.py to _bem.pyc
creating build\bdist.win32\egg\EGG-INFO
copying src\CCBlade.egg-info\PKG-INFO -> build\bdist.win32\egg\EGG-INFO
copying src\CCBlade.egg-info\SOURCES.txt -> build\bdist.win32\egg\EGG-INFO
copying src\CCBlade.egg-info\dependency_links.txt -> build\bdist.win32\egg\EGG-I
NFO
copying src\CCBlade.egg-info\not-zip-safe -> build\bdist.win32\egg\EGG-INFO
copying src\CCBlade.egg-info\requires.txt -> build\bdist.win32\egg\EGG-INFO
copying src\CCBlade.egg-info\top_level.txt -> build\bdist.win32\egg\EGG-INFO
writing build\bdist.win32\egg\EGG-INFO\native_libs.txt
creating 'dist\CCBlade-1.1.1-py2.7-win32.egg' and adding 'build\bdist.win32\egg'
 to it
removing 'build\bdist.win32\egg' (and everything under it)
Processing CCBlade-1.1.1-py2.7-win32.egg
removing 'c:\users\luis miguel\anaconda2\lib\site-packages\CCBlade-1.1.1-py2.7-w
in32.egg' (and everything under it)
creating c:\users\luis miguel\anaconda2\lib\site-packages\CCBlade-1.1.1-py2.7-wi
n32.egg
Extracting CCBlade-1.1.1-py2.7-win32.egg to c:\users\luis miguel\anaconda2\lib\s
ite-packages
CCBlade 1.1.1 is already the active version in easy-install.pth

Installed c:\users\luis miguel\anaconda2\lib\site-packages\ccblade-1.1.1-py2.7-w
in32.egg
Processing dependencies for CCBlade==1.1.1
Searching for airfoilprep.py==0.1.0
Best match: airfoilprep.py 0.1.0
Processing airfoilprep.py-0.1.0-py2.7.egg
airfoilprep.py 0.1.0 is already the active version in easy-install.pth

Using c:\users\luis miguel\anaconda2\lib\site-packages\airfoilprep.py-0.1.0-py2.
7.egg
Finished processing dependencies for CCBlade==1.1.1

(base) C:\CCBlade-master\CCBlade-master>

**Comment by evan-gaertner** [comment]
A fortran compiler was not found, so either A) its not installed, B) its not on your windows Path, or C) you did not configure python to use MinGW.
Also you're not installing in an active Openmdao environment.
Please follow the Wisdem installation instructions very closely as missing any step could cause the installation to fail.

**Comment by Jjzm99** [comment]
Yeah thanks it works, the tests 
But I have a question:

How can I create data files for diferent airfoils or where can I find the data set with more airfoils ?

**Comment by evan-gaertner** [comment]
That's outside the scope of WISDEM and CCBlade.  However, NREL has a large database of airfoil data and a commonly used tool for generating airfoil polars is XFoil.
https://wind.nrel.gov/airfoils/AirfoilData.html
https://web.mit.edu/drela/Public/web/xfoil/
