### ISSUE TITLE
CCBlade Problem with Airfoilprep

### ISSUE THREAD

**Issue by kevin74ha** [WISDEM/CCBlade#17]
During installation either of CCBlade or WISDEM, I always face same problem.
All are related to "airfoilprep".

Problem #1) during installation 
Searching for airfoilprep>=0.1
Reading https://pypi.org/simple/airfoilprep/
Couldn't find index page for 'airfoilprep' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.org/simple/
No local packages or working download links found for airfoilprep>=0.1
error: Could not find suitable distribution for Requirement.parse('airfoilprep>=0.1')

Problem #2)during testing test_ccblade
from airfoilprep import Airfoil
ModuleNotFoundError: No module named 'airfoilprep'

I realized there is no clear connection between airfoilprep and CCblade.

Please let me know how to fix this issue.

Thanks.

BR, Kevin

**Comment by whophil** [comment]
You need to install the airfoilprep package separately.

You can find this package here.
https://github.com/WISDEM/AirfoilPreppy

Follow the instructions in the README file to install into the same environment as CCBlade.

Alternately, the one-liner below will install it for you:
```
pip install git+https://github.com/WISDEM/AirfoilPreppy
```

**Comment by gbarter** [comment]
We have tried to correct these issues by consolidating all of WISDEM repos into one project [here](https://github.com/WISDEM/WISDEM).
