### ISSUE TITLE
Wrong hub loss factor?

### ISSUE THREAD

**Issue by jgeisler0303** [WISDEM/CCBlade#19]
Hi, shouldn't the hub loss factor 
https://github.com/WISDEM/CCBlade/blob/f012a6cbe55d373a562d759e20ce98e1fe80d846/src/ccblade/bem.f90#L68

be ``factorhub = B/2.0_dp*(r - Rhub)/(r*sphi)`` (r instead of Rhub)?

**Comment by gbarter** [comment]
I don't think so.  [See this NREL forum conversation for reference](https://wind.nrel.gov/forum/wind/viewtopic.php?t=482).

**Comment by jgeisler0303** [comment]
OK, thanks for the clarification.

My suggestion wouldn't make sense anyways as it would lead to Fhub never reaching unity.

Still, a strange feeling remains because as it is right now, a hub radius of zero would mean that there is no hub loss at all and a large hub radius would lead to an influence much further out along the blade radius. For "normal" hub radii this formula is probably ok. But I have a suspicion that it is quite heuristic and not 100% physically sound.

**Comment by gbarter** [comment]
At r=0, you don't need a hub loss model as there is no power produced there anyway.  Nevertheless I do agree with you that it feels a little heuristic and ostensibly looks like a bug.  Jason Jonkman's answer linked to above addresses the conceptual difference between a hub-loss model and a tip-loss model.  The current implementation seems like the best practice for moving forward.

**Comment by andrewning** [comment]
With the current formula, at r = Rhub you get maximum hub loss (not no hub loss).  This is a multiplier and with factorhub=0 and Fhub = 0, the loads also drop to 0.  A larger hub would have an influence much further out.

You are right that it is heuristic and not 100% physically sound, although the same is true for the Prandtl tip loss model.  It's a simple model Prandtl proposed and it generally works surprisingly well (though there are various other tip loss models in the literature).  This hub model is just patterned after it.  In the tip model you have the term Rtip/r - 1 (which becomes zero at the tip) and in the hub case it is r/Rhub - 1 (which becomes zero at the hub).

**Comment by jgeisler0303** [comment]
Great. Thanks so much for your detailed explanations. This is more answer than I hoped for, so I'll close the issue.
