### ISSUE TITLE
error in installation

### ISSUE THREAD

**Issue by YingyuXu** [WISDEM/CCBlade#3]
Dear All,

I have downloaded CCBlade in NREL website, and prepare to install it. Before installation, I have installed the Fortran compiler Parallel Studio XE 2011 with VS 2010, Python 2.7.10, numpy 1.8.1, scipy 0.14.0 and zope.interface. But I received the error massage that I stick below.
![default](https://cloud.githubusercontent.com/assets/14290652/9872484/349a8416-5bcc-11e5-9bc6-53f70e0997a1.PNG)

Thank you.

Yingyu Xu

**Comment by andrewning** [comment]
The error says it cannot find a Fortran compiler.  I'm not very familiar with Windows and so can't provide a lot of detail myself, but I know most of our windows users use mingw (or cygwin).  I would recommend going that route.

I'm going to close this, but please reopen if needed.
