### ISSUE TITLE
ImportError: DLL load failed while importing _precomp: The specified module could not be found.

### ISSUE THREAD

**Issue by MuhammadSharjil** [WISDEM/CCBlade#32]
Hi
I am getting the following error while executing test case.

![ccblade](https://github.com/WISDEM/CCBlade/assets/114649993/0388bfae-8d92-4860-9164-2c433c861f5c)

![ccblade1](https://github.com/WISDEM/CCBlade/assets/114649993/99d942e5-667f-496f-998c-99d26162c197)

![ccblade2](https://github.com/WISDEM/CCBlade/assets/114649993/0449073d-0591-4e6d-84a5-9aa06a564784)

Kindly guide me on this.
Thanks

Regards,
Muhammad Sharjil

**Comment by gbarter** [comment]
Your WISDEM install did not succeed.  The quickest resolution would be to just type `conda install wisdem`.  If you need to install from source, then we'll have to see where things went awry using the installation instructions [here](https://github.com/WISDEM/WISDEM/).

**Comment by MuhammadSharjil** [comment]
hi @gbarter 
Thanks for the response.
I have executed 
conda install wisdem

The response I am getting is
![conda_install_wisdem](https://github.com/WISDEM/CCBlade/assets/114649993/e05b2f11-67cb-48d2-adf4-fd9fcbc91c1e)

I actually want to use CCBlade to generate Cp Ct Cq surface for IEA 15MW wind turbine with umaine platform.

Thanks

**Comment by MuhammadSharjil** [comment]
I am using python version 3.10.0

I am getting the following message while activating on windows power shell
![image](https://github.com/WISDEM/CCBlade/assets/114649993/ead26af1-2eca-42af-ab2b-cd805b12d9c4)

**Comment by gbarter** [comment]
You can try dropping the `python=3.10` part of the command.  That might be a bit outdated.

**Comment by MuhammadSharjil** [comment]
Hi @gbarter 
I tried your suggested command and then followed https://wisdem.readthedocs.io/en/master/installation.html#configure-anaconda-environment
![ccblade_2](https://github.com/WISDEM/CCBlade/assets/114649993/8005c856-8cda-4450-a39a-fdc9bc35d513)

When I tried to execute 
cd test
python test_all.py

I got following errors 
![ccblade_3](https://github.com/WISDEM/CCBlade/assets/114649993/600cd735-f93b-4642-a768-7bb6220c75ef)
Can you suggest me how to resolve this.
Thanks

**Comment by gbarter** [comment]
This is very confusing.  Precomp is clearly compiled and available but the code cannot find it.  Also, WISDEM is not installing correctly because it labels the package as UNKNOWN, which is odd.  This could be because the environment is corrupted.  You have pasted the command to create a new environment, but have no used a unique name, so it keeps using the same one.  I would suggest removing the WISDEM folder and the `wisdem-env` environment and starting fresh.  To remove the environment do: `conda remove --name wisdem-env --all`

Are you behind any corporate firewall or security software that might be blocking use of some types of files or programs?

**Comment by MuhammadSharjil** [comment]
Hi
I will check this command and will share the response.
I am using a university connection and as far as I know, my desktop computer is quite at freedom to install these utilities.

Regards,
Muhammad Sharjil

**Comment by MuhammadSharjil** [comment]
hi @gbarter 
I have looked into it and I found that the python was trying to access WindowsApp folder for some kind of installation in C drive, which is not by default allowed by windows 10.
I changed it to avoid the access.
Now I am using Python 3.11.4
![1](https://github.com/WISDEM/CCBlade/assets/114649993/fc2b95a9-6613-4a6e-b27f-c820b36f3338)

![2](https://github.com/WISDEM/CCBlade/assets/114649993/91190568-94ad-4f7f-b49e-1094b4ca70d9)

![3](https://github.com/WISDEM/CCBlade/assets/114649993/6aa3ee35-0b3d-40b8-a77c-41fc2109d618)

![4](https://github.com/WISDEM/CCBlade/assets/114649993/d5773aa3-8369-4719-bd13-dd0df84e00a3)

![5](https://github.com/WISDEM/CCBlade/assets/114649993/cddfff1e-f322-4175-bae5-101792959249)

![6](https://github.com/WISDEM/CCBlade/assets/114649993/fd54b885-352b-4cb4-96d2-05436f63392a)

Can you guide me on this.
Thanks

**Comment by gbarter** [comment]
@MuhammadSharjil : I'm really sorry, but I do not know what is wrong with your installation.  I have not seen that problem before, nor can I recreate it on any of my computers.  I am at a loss of what to suggest to you next and I'm really sorry about that.

Moving forward, it you are comfortable trying the WSL (windows subsystem linux) or have access to a Mac or Linux computer, that tends to be a bit more robust.  I am also hopefull that future WISDEM releases on Windows will be smoother.

**Comment by MuhammadSharjil** [comment]
Hi @gbarter 
Thanks for a detailed response.
I will try to install it on a windows7 os laptop and will share the response.

Thanks
Regards,
Muhammad Sharjil

**Comment by MuhammadSharjil** [comment]
hi @gbarter 
I have managed to get the things going in the right direction fortunately.
I am running the example.py file in 10_ccblade.
I want to ask about the data source of
r = np.array(
I tried matching it with the data in 02_reference_turbines/nreal5mw.yaml components.blade.outer_shape_bem.reference_axis.&ref_axis_blade.z.values
 
![ccblade](https://github.com/WISDEM/CCBlade/assets/114649993/73ff2302-345d-4906-af8b-33976121f3f4)

Can you guide me on this as to how to select the numbers used in example.py for "r" in comparison to the ones provided in nrel5mw.yaml

Thanks

Regards
Muhammad Sharjil

**Comment by gbarter** [comment]
@MuhammadSharjil : I am a bit unclear what the question or concern is.  You are correct in noticing that the values for chord and twist in the CCBlade example are taken from the NREL 5MW reference turbine profile.  However, I don't understand why the chord and twist profiles have to be neatly aligned with the larger yaml-input file for full WISDEM simulation.? You'll notice that the `nrel5mw.yaml` file also has different input grids for the blade shape (the "reference axis") vs the chord and twist profile.  Internal to WISDEM everything is interpolated to a common grid of interpolation points, but no such requirement is placed on the input.

In case it helps, the input grid in the yaml files is non-dimensionalized between 0-1.  You can use these points and the reference axis curve to calculate the radial position.  The CCBlade example species the radial points directly.

**Comment by MuhammadSharjil** [comment]
Hi @gbarter 
I got bit confused by the numbers and just wanted to be sure about the values as to where are these referenced from. 
I compared and found differences in the values and number of data points between BladeSpan, Blade Chord and Blade Twist as given in
a. [r-test](https://github.com/OpenFAST/r-test/tree/b63e9280234c2fb5695a37931d2329f3011e97ec)/[glue-codes](https://github.com/OpenFAST/r-test/tree/b63e9280234c2fb5695a37931d2329f3011e97ec/glue-codes)/[openfast](https://github.com/OpenFAST/r-test/tree/b63e9280234c2fb5695a37931d2329f3011e97ec/glue-codes/openfast)/[5MW_Baseline](https://github.com/OpenFAST/r-test/tree/b63e9280234c2fb5695a37931d2329f3011e97ec/glue-codes/openfast/5MW_Baseline)
/NRELOffshrBsline5MW_AeroDyn_blade.dat
b. [WISDEM](https://github.com/WISDEM/WISDEM/tree/master)/[examples](https://github.com/WISDEM/WISDEM/tree/master/examples)/[10_ccblade](https://github.com/WISDEM/WISDEM/tree/master/examples/10_ccblade)
/example.py

<img width="427" alt="Screenshot 2024-03-07 at 10 07 42" src="https://github.com/WISDEM/CCBlade/assets/114649993/a6f23384-91bc-4af4-b2f3-092e01fe55aa">
<img width="427" alt="Screenshot 2024-03-07 at 10 09 58" src="https://github.com/WISDEM/CCBlade/assets/114649993/1a6b25cd-4c94-4c9d-8893-131b20d1cbc0">
<img width="427" alt="Screenshot 2024-03-07 at 10 10 22" src="https://github.com/WISDEM/CCBlade/assets/114649993/9a791d15-383b-43a7-832b-cf1e72538c85">


I actually want to use ccblade to get get Cp, Ct and Cq values for iea 15MW wind turbine. But I am not sure about which numbers to plug in from https://github.com/IEAWindTask37/IEA-15-240-RWT/blob/master/OpenFAST/IEA-15-240-RWT/IEA-15-240-RWT_AeroDyn15_blade.dat

Thanks

Regards,
Muhammad Sharjil

**Comment by MuhammadSharjil** [comment]
Hi @gbarter 
I used Aerodyn_driver and Openfast to get Cp, Ct and Cq for IEA 15MW. The numbers I got were not in comparison with the https://github.com/IEAWindTask37/IEA-15-240-RWT/blob/master/OpenFAST/IEA-15-240-RWT/Cp_Ct_Cq.IEA15MW.txt
which used ccblade (https://wes.copernicus.org/articles/7/53/2022/wes-7-53-2022-discussion.html)
I will try the numbers you have suggested to get some results.

Thanks
Regards,
Muhammad Sharjil

**Comment by wodetouzi** [comment]
> Hi @gbarter Thanks for a detailed response. I made some further attempt and finally digout the issue. I dont know why this was happening but it was somewhat causing the problem. _mamba activate wisdem-env_ was not activating the _wisdem-env_ I tried _conda activate wisdem-env_ also but it didnt work. Even trying to delete the environment with _conda remove --name wisdem-env --all_ was not deleting the wisdem-env. Afterwards executing _conda env list_ was still showing wisdem-env I then used the absolute path in conda remove command to reference the environment . It removed the wisdem-env
> 
> I then made a a fresh attempt to go through WISDEM Installation. Now only using absolute path for environment activation is enabling the _wisdem-env_. I am able to execute _python test_all.py_ I am now facing this issue that the 16GB ram windows 10 system is crashing in between the process.
> 
> ![ccblade1](https://private-user-images.githubusercontent.com/114649993/309769975-a205fb89-34a6-4cef-97c7-a76962558514.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0MzQ2MDAsIm5iZiI6MTcxMTQzNDMwMCwicGF0aCI6Ii8xMTQ2NDk5OTMvMzA5NzY5OTc1LWEyMDVmYjg5LTM0YTYtNGNlZi05N2M3LWE3Njk2MjU1ODUxNC5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNlQwNjI1MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMmU5NmYxYWFjZGZjOGI4NjE4MzdjZGE3NGZmM2NiMGE4ZjYxOTYzYjU4MWMxNTM0ZDFhNDExYmYxMjAxODBlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.quu1jYLZPfDmD15fU_DjOIoVkSXrbq39LAO-lKYp89g)
> 
> Can you guide me on this. Thanks
> 
> Thanks Regards, Muhammad Sharjil

Hi Muhammad, I am facing exactly the same problem as you were. Could you please explain more about how to remove the wisdem-env using an absolute path?
Best regards,
wodetouzi

**Comment by gbarter** [comment]
I believe if you type `conda env list` it will give you the full path to the environments, and then you can manually delete those directories.  I think there is also a `.conda/environments.txt` file in your home directory that needs to be updated. 
 Be wary that this manual approach might cause some issues and `conda remove --name <envname> --all` is best.

**Comment by MuhammadSharjil** [comment]
> > Hi @gbarter Thanks for a detailed response. I made some further attempt and finally digout the issue. I dont know why this was happening but it was somewhat causing the problem. _mamba activate wisdem-env_ was not activating the _wisdem-env_ I tried _conda activate wisdem-env_ also but it didnt work. Even trying to delete the environment with _conda remove --name wisdem-env --all_ was not deleting the wisdem-env. Afterwards executing _conda env list_ was still showing wisdem-env I then used the absolute path in conda remove command to reference the environment . It removed the wisdem-env
> > I then made a a fresh attempt to go through WISDEM Installation. Now only using absolute path for environment activation is enabling the _wisdem-env_. I am able to execute _python test_all.py_ I am now facing this issue that the 16GB ram windows 10 system is crashing in between the process.
> > ![ccblade1](https://private-user-images.githubusercontent.com/114649993/309769975-a205fb89-34a6-4cef-97c7-a76962558514.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0MzQ2MDAsIm5iZiI6MTcxMTQzNDMwMCwicGF0aCI6Ii8xMTQ2NDk5OTMvMzA5NzY5OTc1LWEyMDVmYjg5LTM0YTYtNGNlZi05N2M3LWE3Njk2MjU1ODUxNC5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNlQwNjI1MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMmU5NmYxYWFjZGZjOGI4NjE4MzdjZGE3NGZmM2NiMGE4ZjYxOTYzYjU4MWMxNTM0ZDFhNDExYmYxMjAxODBlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.quu1jYLZPfDmD15fU_DjOIoVkSXrbq39LAO-lKYp89g)
> > Can you guide me on this. Thanks
> > Thanks Regards, Muhammad Sharjil
> 
> Hi Muhammad, I am facing exactly the same problem as you were. Could you please explain more about how to remove the wisdem-env using an absolute path? Best regards, wodetouzi

@wodetouzi ,
conda info --envs
This will give you the complete path of environments
Then you can copy the full path of environment from the list which you want to remove 
conda remove --name -p <environment path> --all
i.e.
conda remove --name -p C:\ProgramData\miniforge3\envs\wisdem-env --all
![conda](https://github.com/WISDEM/CCBlade/assets/114649993/89b47fad-6dcb-4396-9d66-42a3928e4641)

**Comment by gbarter** [comment]
This should be resolved in the latest version of WISDEM
