### ISSUE TITLE
Installation and unit test fails...

### ISSUE THREAD

**Issue by SaschaErbsloeh** [WISDEM/CCBlade#4]
Hi,

am trying to install ccblade on my Mac. I have installed Python 3.5.2 using Anaconda with which I downloaded your mentioned prerequisites. During installation the notable error message is: 

warning: no directories found matching 'docs/_build/html'

For the test I also receive an error:

Saschas-MBP:WISDEM-CCBlade-f5b6d83 s.d.e$ python test/test_ccblade.py
Traceback (most recent call last):
  File "test/test_ccblade.py", line 20, in <module>
    from ccblade import CCAirfoil, CCBlade
  File "//anaconda/lib/python3.5/site-packages/CCBlade-1.1.1-py3.5-macosx-10.6-x86_64.egg/ccblade.py", line 1081
    print CP, CT, CQ
           ^
SyntaxError: Missing parentheses in call to 'print'

I have made no alteration to the code in any way. Any help would be much appreciated.

Sascha

**Comment by andrewning** [comment]
This was written for Python 2.  In the case of the print statement the Python 3 syntax is:
`print(CP, CT, CQ)`.  You may have to make other changes if you wish to use Python 3.
