### ISSUE TITLE
Segfault on Ubuntu using gfortran

### ISSUE THREAD

**Issue by ha-ko** [WISDEM/CCBlade#5]
Hi,

hope this project is still alive. :)
I used gfortran 5.4.0 to compile the bem module.
Both unit tests end in an segmentation fault.
It can be fixed by reverting 21eaeabe2791316c824a93995b0fddc8f02bde03

**Comment by andrewning** [comment]
Thanks for the report. We've often built from master on ubuntu so I'm not sure what the issue is in this case but will keep it in mind.

**Comment by emerrf** [comment]
I managed to run the code and tests from current master branch without issues in Ubuntu 16.04 LTS and even in Windows 10 using Anaconda2. For instructions checkout my fork: https://github.com/emerrf/CCBlade/tree/packaging-refactored
Btw, I refactored the package so it can be pip installed as a dependency in other projects. I am happy to contribute back with a PR. Congratulations for the awesome job!

**Comment by dykesk** [comment]
@emerrf - thanks for the offer; it would be great to have this contribution; @andrewning  - can you checkout this pull request and merge as appropriate?

**Comment by emerrf** [comment]
@dykesk thanks for your reply. I just added the PR #7 for @andrewning
