### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by efe011** [WISDEM/CCBlade#8]
Hello,

I'm getting the following error when using "run setup.py install" from the iPython console, under Windows 10: 

"build\temp.win-amd64-2.7\Release\src\bem.o : fatal error LNK1112: module machine type 'X86' conflicts with target machine type 'x64'
An exception has occurred, use %tb to see the full traceback."

Any hints on how could I solve this?

Thank you very much.

**Comment by dykesk** [comment]
This is hard to address without more information - its a linking issue most likely related to the types of compilers you are using; if you have not yet, check out the detailed windows install instructions available in nwtc.nrel.gov/wisdem

**Comment by leobwind** [comment]
Hi Katherine and Efe011,
 sorry for reopening a closed issue. I'm posting my solution, maybe it can be useful to somebody else in the future.
I had a similar problem, and after some struggling it seems to boil down to: **Install Anaconda 2 - 32 bit" :
1. Install Anaconda2 -32 bit, it will appear as another conda environment in your Anaconda navigator.
2. Install for that environment the missing packages (eg. zope.interface)
3. Activate the environment corresponding to that by opening the corresponding terminal
4. Carry out the `python setup.py install` from there.
5. Somehow it seems that new created "Egg" directories are not found automatically by python, add them to your Python Path by typing in the same terminal something like: `set pythonpath=c:\ProgramData\Anaconda2\Lib\site-packages\AirfoilPrep.py-0.1.0-py2.7.egg\airfoilprep\;c:\ProgramData\Anaconda2\Lib\site-packages\CCBlade-1.1.1-py2.7-win32.egg\ccblade\` (path depends on your installation, there is probably a more elegant way to do that, suggestions are welcome).
6. Yep, now ready to run the test, everything will be fine :)

Hope it might help,
Cheers,
Leonardo
