### ISSUE TITLE
CCBlade Installation issue LINUX

### ISSUE THREAD

**Issue by SamAct** [WISDEM/CCBlade#9]
Hello,
Trying to install WISDEM on ubuntu, when i encountered this issue in CCBlade.
 I installed all the requirements using something link this:
`sudo apt-get install libblas-dev liblapack-dev` etc.

The end log of WISDEM reads:
`WISDEM 0.1.1 is already the active version in easy-install.pth`
`Installed /home/sam/Documents/openmdao-0.10.3.2/WISDEM/src`
`Attempted to install WISDEM and its sub-plugins:  ['Turbine_CostsSE', 'CommonSE', 'Plant_CostsSE', ``'Plant_FinanceSE', 'Plant_EnergySE', 'AeroelasticSE', 'AirfoilPreppy', 'CCBlade', 'DriveSE', ``'DriveWPACT', 'NREL_CSM', 'RotorSE', 'TowerSE', 'pyFrame3DD', 'JacketSE', 'akima', 'pBEAM']`
`Failed to install:  []`
 
Hoping  this means all plugins are installed.
I run this test--
`(openmdao-0.10.3.2)sam@sam-Linux:~/Documents/openmdao-0.10.3.2/WISDEM$ python src/test/test_turbine_gradients.py`

The test output reads:

`(openmdao-0.10.3.2)sam@sam-Linux:~/Documents/openmdao-0.10.3.2/WISDEM/src/test$ python test_turbine_gradients.py``
/home/sam/Documents/openmdao-0.10.3.2/lib/python2.7/site-packages/openmdao.main-0.10.3.2-py2.7.egg/openmdao/main/publisher.py:12: VisibleDeprecationWarning: zmq.eventloop.minitornado is deprecated in pyzmq 14.0 and will be removed.`
   ` Install tornado itself to use zmq with the tornado IOLoop.`
    
 ` from zmq.eventloop import zmqstream`
`Traceback (most recent call last):`
 ` File "test_turbine_gradients.py", line 13, in <module>
    from wisdem.turbinese.turbine import MaxTipDeflection`
  `File "/home/anurag/Documents/openmdao-0.10.3.2/WISDEM/src/wisdem/turbinese/turbine.py", line 15, in <module>`
   ` from rotorse.rotor import RotorSE`
 ` File "/home/anurag/Documents/openmdao-0.10.3.2/WISDEM/plugins/RotorSE/src/rotorse/rotor.py", line 17, in <module>`
   ` from rotoraerodefaults import CCBladeGeometry, CCBlade, CSMDrivetrain, RayleighCDF, WeibullWithMeanCDF`
  `File "/home/anurag/Documents/openmdao-0.10.3.2/WISDEM/plugins/RotorSE/src/rotorse``/rotoraerodefaults.py", line 15, in <module>`
    `from ccblade import CCAirfoil, CCBlade as CCBlade_PY`
`ImportError: cannot import name CCBlade`

CCAirfoil was imported but not CCBlade. 
`from ccblade import CCAirfoil`
ccblade doesnt seem to import CCBlade.

And I get this error, although python `zmq` is installed.

The following seems to be working-
`import wisdem.lcoe.lcoe_csm_assembly`

but not:
`import wisdem.lcoe.lcoe_se_assembly`
`import wisdem.turbinese.turbine`

Please suggest what went wrong.

**Comment by kilojoules** [comment]
@SamAct Did you get past this? I've been getting the CCBlade import error too...
